image: curlimages/curl:latest

minimize_deploy:
  stage: deploy
  tags:
    - linuxdocker
  script:
    - "curl -X POST --fail -F token=${GITLAB_TRIGGER_PIPELINE_TOKEN} -F ref=master -F variables[IHB_JSON_NAME]=4-USB-2.0-Hub-based-on-SL2.1A https://gitlab.soraharu.com/api/v4/projects/34/trigger/pipeline"
